services: 
  db: 
    container_name: "test_db"
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports: 
      - "3307:3306"
    environment: 
      MYSQL_DATABASE: "test_db"
      MYSQL_RANDOM_ROOT_PASSWORD: "password"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "password"
    volumes: 
      - mysql_data:/var/lib/mysql_data
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
  api: 
    container_name: "test-api"
    build: 
      context: .
      dockerfile: api.Dockerfile
    depends_on: 
      - db
    ports: 
      - "8080:8080"
    volumes: 
      - ".:/app/"
networks:
  default:
volumes: 
  mysql_data:
